### ISSUE TITLE
Way to Visually Represent Rush Jobs

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#117]
Using a styled label component : 
http://kpowz.github.io/gus-bootstrap/components/#labels

I've given this a go : 
![screen shot 2015-03-01 at 8 02 41 pm](https://cloud.githubusercontent.com/assets/1749783/6434430/5fe53f68-c04e-11e4-97ac-96c96ad3e69d.png)

What do you think @benjanders , @spacecowboy88 ?

One thing that's not ideal about the way 'RUSH' classification is treated historically is that even though (i'd think) it effectively becomes irrelevant after successfully printed, that classification will stick with the job...

**Comment by benjanders** [comment]
I like the way the rush is conveyed. It is probably ok for the classification to stick with the job. We can probably start to see trends with certain customers.

**Comment by kPOWz** [comment]
we can always iterate from here if it ends up not working great.  Solarz reminded me another label we might have in the future is 'incomplete' or 'incomplete info' (meaning more info / data entry needed on the job)
