### ISSUE TITLE
Capture Ink Colors & Display on Paul Print View

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#124]

**Comment by kPOWz** [comment]
"We just need a text box to capture ink color. It doesn't need to reference anything. I think "held space" is the correct term."

@benjanders - from what I'm seeing ink color(s) have never been captured in the past , so will need to break this out as a task to create a new field(s) in the database and link up through UI. If true that just free-form text is all we need (not tied to front/back/sleeve, etc...), shouldn't be a big deal.

**Comment by benjanders** [comment]
This won't need to reference back to anything in the database. Just a free-form text box is fine.

**Comment by kPOWz** [comment]
ok, got it.  Held space on the Paul print view  ✅
