### ISSUE TITLE
New Job - Garment Quick Add Shadowbox

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#17]
If a user is creating a job, and the needed garment(or color) does not exist, the user must currently 1) exit job, 2) create garment, potentially 3) create colors, 4) back to "New Job." Ideally there would be a way to add a garment within the "new job" page. Basically take the "add garment" page and make it available within the "new job" page.

**Comment by kPOWz** [comment]
Working on this now - will commit when issue with vendor list  is solved.  May be a good place to start w/ a redesign.

**Comment by kPOWz** [comment]
This form is working now - will push to live site tomorrow AM. 

Would like to add to this so that after the create product dialog auto-closes upon success the newly created product is already selected / chosen in drop-down.

**Comment by benjanders** [comment]
This is freaking awesome. The boys are in love.
