### ISSUE TITLE
New Job - More info needed error message

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#18]
Sometimes users will not include all of the necessary information when they create a new job. This is either because they do not have the information, or because they are lazy and just want to create a job quickly. When they click create job, and error message should let them know they need more information.

**Comment by kPOWz** [comment]
job form front , back , sleeve (total passes)  ; repercussions on calendar , add garment quoted price ; make sure they want to leave these blank!

Sometimes there's a good reason these aren't being filled in!
