### ISSUE TITLE
Duplicate Sizes on Mary's Meals Job (job/671)

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#22]
Observed in Job Page for Mary's Meals (#671), garment sizes are listed twice, with differing numbers on each list. I know quantity and numbers have been edited at least once for that specific job. Issue was first noticed Monday morning, after an update was deployed the previous Friday. May or may not be related.

**Comment by kPOWz** [comment]
This looks like its a bug with all jobs possibly tied to edits/updates on the order.

**Comment by kPOWz** [comment]
This was related to any job that had multiple styles (i.e. more than one garment type)

**Comment by benjanders** [comment]
What! It's happening again! Specifically with the job "Goldies." Thoughts?

**Comment by kPOWz** [comment]
This is occurring where style is the same & only color is different. Fix on the way!
