### ISSUE TITLE
All Jobs - Search Bar

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#23]
Add a search bar for jobs, by job name, email, or client name.

**Comment by kPOWz** [comment]
This should go cross status.

**Comment by kPOWz** [comment]
search jobs, vendors, products

**Comment by kPOWz** [comment]
Users can search by job name & client's company name in first iteration.  We'll go from there.  Have initially limited the search results to 25 for the drop-down display pattern.

For now, the search bar is placed atop the all jobs page.

**Comment by kPOWz** [comment]
Search by email address, name & phone number as well
