### ISSUE TITLE
All Jobs - Tabs

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#24]
Currently "Current Jobs, Completed Jobs, and Cancelled Jobs." Update to  tabs for "Created, Ordered, Counted, Printed, Invoiced, Completed." Jobs to be sorted into tabs by current status.

**Comment by kPOWz** [comment]
" "Created, Ordered, Counted, Printed, Invoiced, Completed." " 

Ben, please confirm - get rid of the Canceled tab ?

**Comment by kPOWz** [comment]
I left 'Canceled' in just to be safe.  Please let me know if you'd like that tab removed!
