### ISSUE TITLE
Add Colors - Upside down list

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#27]
This might be a layout design issue, but colors have to be added at the bottom of the page, instead of the top of the page.

**Comment by kPOWz** [comment]
Not sure I follow. Are we talking the new 'add product pop-up' Any chance you could attach a screen shot of the mix-up?

**Comment by benjanders** [comment]
![Picture 1](https://f.cloud.github.com/assets/3011006/23070/48b45bb6-4a22-11e2-849a-95603fc3a748.png)

I think we talked about this, the text field should be at the top of the page, not at the bottom. Is that a problem for Solarz?

**Comment by kPOWz** [comment]
Ah yes!

Thanks for remembering that. 

This change is live!
