### ISSUE TITLE
Design File Check Broken

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#29]
design/ print art file are saved to the Gus database as type 182 (image) or 183 (design), but a set of old constants mapping to values 106 & 107 are still being used in the code to check for files associated with a job. 

This check will erroneously returned 'false - no design files associated w/ job' no matter what. 

A good, recent example of this is job 'SubZero[S]' viewed at the following url : http://gus.87c.us/job/703.  Even though a file called 'finalmockup.jpg' was uploaded & is on the sever, since the check is broken, this file isn't listed nor downloadable from the view as we expect it to be.

**Comment by benjanders** [comment]
After a lot of discussion and debate, we have decided that storing design and art files within Gus will get entirely too complex and will not be used. 

Hopefully you didn't complete the Design File Upload.
