### ISSUE TITLE
Delete Job Broken

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#30]
![Picture 30](https://f.cloud.github.com/assets/1749783/36991/b7c52704-5398-11e2-8c95-90c7b54bb992.png)

As far as I can tell, jobs cannot be deleted because the cascade relationships are not set up correctly.

**Comment by benjanders** [comment]
Ah! Probably a HUGE oversight, but I guess we just never addressed deleting jobs. I honestly have no idea why we choose "cancel" instead of "delete." Is it possible to change the cancel to do the job of delete? We don't have any reason to keep jobs around after they have been cancelled.

**Comment by kPOWz** [comment]
Yes, absolutely possible. 

Who can delete jobs? 
Administrator?  
Project Lead?  
Printer?    

If a job is deleted, is it ok?, preferred? to delete any associated artwork?
 On this one I would say yes, but when associated artwork is detected, warn the person performing the delete that if they have use/need for the artwork they should confirm it is stored elsewhere (sounds like for 8|7 that is Dropbox right now). 

Last, may be important to note that I attempted the job delete from this url : http://gus.87c.us/job/admin & don't believe 8|7 Gus admins actively use that admin panel in Gus.

**Comment by benjanders** [comment]
I would say project managers and administrators can cancel jobs. I would say delete the artwork as well. But have a confirmation box that asks the user to back the artwork up elsewhere. So basically just like you said.

**Comment by kPOWz** [comment]
@benjanders , @alliefayden  - this looks like its becoming important in keeping GUS clean and organized; it also relates to #85. I'm done with #85, but the basic delete functionality is still broken.  Time to re-open this one ?
