### ISSUE TITLE
Job Due Date & Print Date Defaults

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#39]
A lot is going on with the three different types of dates associated with a job (print date, due date, & pickup date). 

Due date doesn't seem to be used at all, but when you view a job, new to 'DUE' is actually the pickup date.

Print date is getting set to whatever pickup date is chosen by the person who creates the job (even if pickup date null / not set).

Also, in the all jobs list it's the print date that gets displayed. 

To start addressing some of these quirks, Ben has asked that the print date automatically get assigned to two weeks from the current day (day job is created).

**Comment by kPOWz** [comment]
Should the 'two weeks' be nearest weekday at least two weeks from now or is any day of the week fine?

**Comment by kPOWz** [comment]
For now, I'm still going to let the job creator pick a pickup date, but then automatically assign the print date separately.

This means, when viewing the job you'll see both the pickup date(whatever user chose) and the print date (two weeks from job creation).  Also when viewing the job in the jobs by status list you still see just the print date.

We can see how this goes and I'll adjust accordingly.

**Comment by kPOWz** [comment]
Do you want the print date editable?

**Comment by kPOWz** [comment]
Ben, please review this change & let me know if it's satisfactory.  There are  a couple questions above - only address if need be. Thanks!

**Comment by benjanders** [comment]
Ben: Define Print date vs. Pick up date. Define calendar

**Comment by kPOWz** [comment]
Ben's comments : 

Here's my solution to the Print Date, Due Date, Pickup Date debacle. Easier to explain in person, but I'll try.

Strip all current uses of the Due date from Gus. It was used for an outdated calendar and is no longer necessary.

The Pickup date gets renamed as the Due Date. Same functionality, but I like the term due date better than pickup date.

Due Date is still established in the New Job page(current functionality). Print date automatically defaults to reflect the Due Date.

The Calendar will display jobs according to their Print Date. Inside the calendar, the Print Date is editable to any date prior to Due Date.

Summed up: Due Date is a hard date that the job must be completed. Print Date is a fluctuating date used for production scheduling. Print Date is kind of a slave to the Due Date.

We can talk more tomorrow.

**Comment by kPOWz** [comment]
anytime due date gets update, match the slave (the print date to it) 

drag & drop is good!

**Comment by kPOWz** [comment]
also need client side validator that rejects drop if new print date > current due date (on calendar)
