### ISSUE TITLE
Screen Fee Edits Not Sticking

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#47]
"Sometimes it doesn't take the screen fee off even if I delete it"

I couldn't recreate this - both editing the set up fee later & making it different than the default during creation both worked fine for me, so, Ben, I think I just need a little better description of how to recreate this.  

For example, 
By 'taking screen fee off' does that mean just setting it to zero on the job?
Where do you still see the screen fee?  & is it always $30 in these situations when it's supposed to be gone?

I believe what we'll wind up with here is that you guys just want the application of the default to work differently by just setting the fee to $30 initially and then editable (when garment # conditions are met) rather than being strictly enforced if no Setup Fee is set. Related problems I see include the fact that setup fee is a fixed price in your QB setup & that when it's going to be charged the job view doesn't reflect that.

With the term 'screen fee' we're talking about what's called the 'SET UP FEE' in Gus, correct?

**Comment by benjanders** [comment]
Change set up fee to checkbox. Eliminate garment count rule.

**Comment by kPOWz** [comment]
Looked this over with Ben. Need to switch the default to unchecked - which is equivalent to the $30 fee waived.
