### ISSUE TITLE
New Product - Success and Error Messages Not Working

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#51]
In the code it looks like there should be either a success or error message returned after a user attempts to add a product (just like the behavior after all the other submit buttons), but in my experience this is not happening.

**Comment by benjanders** [comment]
That should be there, but we completely overlooked the Success/Error functionality when we were building the site originally. We went back and added the message on the New Job page, but I'm not sure if that got added to any other pages. You are correct that it should happen.

**Comment by kPOWz** [comment]
Every time a product is created or updated should there always be at least one size & at least one color ?  Or is it ok for users to create a product without one or both of those sets of data ?

**Comment by kPOWz** [comment]
fixed.
