### ISSUE TITLE
Products Not Unique

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#52]
Add product (and the data structure supporting it) allows multiple products with the same Item ID given a particular vendor. 

Gus should be enforcing unique Item IDs per vendor & possibly across the board (not by vendor - just unique in total). 

Ben, what is a reasonable rule for keeping the product data clean & without duplicates?

**Comment by benjanders** [comment]
Item IDs should definitely be unique. I think that is another thing that was simply an amateur mistake.
