### ISSUE TITLE
Create New Job Error 500

### ISSUE THREAD

**Issue by benjanders** [kPOWz/Deviner#65]
I just created a new job and got the following error message.
![picture 2](https://f.cloud.github.com/assets/3011006/519834/f64749a8-bf22-11e2-88a0-876a9bb50cc8.png)

The job was created successfully, I don't know what the message means.

**Comment by kPOWz** [comment]
Hey Ben, 

I opened an issue for this same error earlier here  : https://github.com/kPOWz/Deviner/issues/60, so I'm going to go ahead and close this one.

When I saw it, the success message proved correct in that the new job is created successfully. Please let me no if that is not what you're experiencing as well!
