### ISSUE TITLE
My Jobs Calendar - Make Led Jobs No Time Restriction

### ISSUE THREAD

**Issue by kPOWz** [kPOWz/Deviner#68]
right now it's a week ; let's try out a month

ideally, we'd also conditionally hide the list if you don't have the leader role

**Comment by kPOWz** [comment]
What else did we want to add or remove here ?

1) I know we wanted each job to link directly to its edit page( & step 2 to just dynamically expand as edit), but what else did we want to remove (or add) ? 

I think we wanted to remove :
    the separator with the 3 links (New Job , All Jobs, Past Jobs)
    the passes col
    the art col
    the sizes col
I also thought (besides edit action) there was a column we wanted to add - what was it ? 

2) Should this job list be ordered by print date , due date or other ? 

3) Should this job list include status 'COMPLETED' jobs ?  (currently, does not)

![picture 44](https://f.cloud.github.com/assets/1749783/779477/164db940-e9d9-11e2-9f13-67e4881ce2b7.png)

**Comment by benjanders** [comment]
1) I know we wanted each job to link directly to its edit page( & step 2 to just dynamically expand as edit), but what else did we want to remove (or add) ?

I think we wanted to remove :
the separator with the 3 links (New Job , All Jobs, Past Jobs) - YES
the passes col- YES
the art col- YES
the sizes col- YES
I also thought (besides edit action) there was a column we wanted to add - what was it ? - LEADER, if I remember correctly. 

2) Should this job list be ordered by print date , due date or other ? - It might change, but what about the idea of alphabetically by Job Name?  

3) Should this job list include status 'COMPLETED' jobs ? (currently, does not) - NO it should not.
