### ISSUE TITLE
Combined job view and edit view pages

### ISSUE THREAD

**Issue by johnsolarz** [kPOWz/Deviner#81]
Creating a single editable "job view".

**Comment by kPOWz** [comment]
The actions (view invoice, export to quickbooks) currently available from view job only should transfer over to the combined view, correct ?
![screen shot 2014-07-12 at 4 25 51 pm](https://cloud.githubusercontent.com/assets/1749783/3562826/4801bdf8-0a0b-11e4-9b04-8172f0a54834.png)

**Comment by kPOWz** [comment]
deployed progress commit to test, with desired behavior in place, but the 'view' code is still there just not used. 

Waiting on answer to 'view invoice' & 'export to quickbooks' actions to finish up.

**Comment by kPOWz** [comment]
based on the mockups I think the answer to my question is actually a 'no', but would still like to confirm with @johnsolarz  or @benjanders ...

**Comment by kPOWz** [comment]
in progress
