### ISSUE TITLE
Login Page: Removing some content

### ISSUE THREAD

**Issue by alliefayden** [kPOWz/Deviner#82]
Removing everything except for: 
-Email Address Field
-Password Field
-Remember Me Next Time Option
-Login Button

Replacing: 
"Login" heading with "Gus" heading

**Comment by kPOWz** [comment]
This causes 'GUS' to be displayed twice as its part of the main layout as well.  Check it out in test and let me know, @alliefayden  if there's an alternative solution desired.

**Comment by kPOWz** [comment]
having the full prototype has answered the question
