### ISSUE TITLE
Sidebar: User Area

### ISSUE THREAD

**Issue by alliefayden** [kPOWz/Deviner#83]
The bottom of the sidebar will be an area for the user to view their stats and get to secondary links:

Additions:
-Cost of goods and monthly sales of the user to the bottom of the sidebar
-Second-hand links to be tucked into a drop down menu. The drop-down menu would be activated upon clicking a settings icon/button (Add Product, Add User, Add Vendor, Colors etc, View Customers, View Products, View Users, View Vendors)

**Comment by kPOWz** [comment]
Would you attach or link an approximate prototype here? I want to see how much of this I can get done w/out the styling changes already in place.

**Comment by alliefayden** [comment]
Of course! I've attached a full page mockup, and a more detailed portion of the sidebar. 

![screen shot 2014-07-14 at 9 48 35 am](https://cloud.githubusercontent.com/assets/7141116/3572260/f74dc076-0b65-11e4-9221-f966eb986d1c.png)
![screen shot 2014-07-14 at 9 48 19 am](https://cloud.githubusercontent.com/assets/7141116/3572261/f74eab30-0b65-11e4-9db0-45ac3e2ac396.png)

**Comment by kPOWz** [comment]
closed #83 with  aac7f31dde2b62101bfb583f7100230ed1e082ae
