### ISSUE TITLE
My Jobs Page: Notification bar

### ISSUE THREAD

**Issue by alliefayden** [kPOWz/Deviner#84]
Creating a notification bar to appear at the top of the My Jobs page upon login, with a button to dismiss the notification.

Notification Bar: "Welcome, Name! You have 36 jobs. Here are your monthly sales: $15,054. Your Cost of Goods percentage for the month is 89%. Keep doin' whatcha do!"

**Comment by kPOWz** [comment]
close #84 with 629e9ed2964b1b39a3ad06e9af0a629613668e78
