### ISSUE TITLE
All Jobs & My Jobs Page Additions

### ISSUE THREAD

**Issue by alliefayden** [kPOWz/Deviner#85]
Additions:
- Delete job button
- Edit job button

**Comment by kPOWz** [comment]
Any special rules needed for what users can delete jobs ?  (for example, should the user need the 'leader' role?)

See past discussion : https://github.com/kPOWz/Deviner/issues/30

**Comment by kPOWz** [comment]
Allie, please check these changes out in the test environment & let me know what you think before I deploy to the live environment. thanks!

**Comment by benjanders** [comment]
It makes sense that the job lead and the admin should be the only ones to
delete jobs. Sound good?
