### ISSUE TITLE
Add Dynamic, Auto-Calculated Total to Job Form

### ISSUE THREAD

**Issue by alliefayden** [kPOWz/Deviner#86]

**Comment by kPOWz** [comment]
Are additions 1-4 all/some action items for me @alliefayden ? 

If so, please attach or link an approximate prototype.

Will size this task or break it down & size after seeing the proto

**Comment by kPOWz** [comment]
added the status+safe button group tonight, but since none of BS css or javascript is in place, i also made this fiddle to give a better example of what will remain to style on top of the bootstrap base : http://jsfiddle.net/kpowz/oc41pvq1/
